services:
  app:
    build: .
    container_name: node_app
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=db
      - PGDATABASE=fullcycle
      - PGPORT=5432
    expose:
      - "8081"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fullcycle
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: always

volumes:
  pgdata: